[build]
  # This command runs your existing build script
  command = "pnpm build"
  # The directory where your built frontend is located
  publish = "dist/spa"
  # The directory where your serverless function will be
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200